from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    signup_view,
    login_view,
    google_auth_view,
    logout_view,
    verify_otp_view,
    resend_otp_view,
    profile_detail_update_view,
    forgot_password_view,
    change_password_view,
    add_password_view,
    reset_password_view,
    admin_lawyer_list_view,
    admin_lawyer_verify_view,
    admin_promote_user_view,
    admin_create_admin_user_view,
    admin_delete_lawyer_view,
    search_users_view,
    lawyer_profile_completion_view,
)

urlpatterns = [
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("google/", google_auth_view, name="google_auth"),
    path("verify-otp/", verify_otp_view, name="verify_otp"),
    path("resend-otp/", resend_otp_view, name="resend_otp"),
    path("profile/", profile_detail_update_view, name="profile"),
    path("logout/", logout_view, name="logout"),
    path("forgot-password/", forgot_password_view, name="forgot_password"),
    path("reset-password/", reset_password_view, name="reset_password"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("change-password/", change_password_view, name="change_password"),
    path("add-password/", add_password_view, name="add_password"),
    path("search-users/", search_users_view, name="search_users"),
    path("lawyer-profile-complete/", lawyer_profile_completion_view, name="lawyer_profile_completion"),
    path("admin/lawyers/", admin_lawyer_list_view, name="admin_lawyer_list"),
    path(
        "admin/lawyers/<str:lawyer_id>/verify/",
        admin_lawyer_verify_view,
        name="admin_lawyer_verify",
    ),
    path("admin/users/promote/", admin_promote_user_view, name="admin_promote_user"),
    path(
        "admin/users/create-admin/",
        admin_create_admin_user_view,
        name="admin_create_admin_user",
    ),
    path(
        "admin/lawyers/<str:lawyer_id>/delete/",
        admin_delete_lawyer_view,
        name="admin_lawyer_delete",
    ),
]